### ISSUE TITLE
Flutterwave Services should return promises if callback is missing

### ISSUE THREAD

**Issue by perfectmak** [Flutterwave/flutterwave-node#3]
I noticed that the services exposed by flutterwave uses callbacks to send response, while this is good. I feel they should also return a Promise if the callback is missing.

If this feature is accepted, I wouldn't mind sending in a PR for this.

Thank you.

**Comment by 4y0** [comment]
Hello @perfectmak , that'd be awesome. Please do  :)

**Comment by perfectmak** [comment]
Okay @4y0, I'll arrange a PR for this ASAP.

**Comment by 4y0** [comment]
Thanks @perfectmak
