### ISSUE TITLE
authmodel "Random_debit" - not working

### ISSUE THREAD

**Issue by codeNgamer** [Flutterwave/flutterwave-node#7]
I'm trying to tokenize a card using "Random_Debit" model but I get the response "Sorry unknown Authentication model". any ideas?? sample code below:

`
  flutterwaveClient.Card.tokenize({
    cardno,
    cvv,
    expirymonth,
    expiryyear,
    authmodel: "RANDOM_DEBIT",  
    validateoption: "SMS|VOICE",
  }, callback);
`

**Comment by 4y0** [comment]
Hi @codeNgamer please note that `NOAUTH`  and `BVN` are the only accepted authentication models for the tokenisation endpoint. You can read more about this here https://www.flutterwave.com/documentation/card-payments-with-preauth/#tokenize

**Comment by codeNgamer** [comment]
@4y0 Ahh gotcha, closing now. Unrelated question though, know anyway to change a phone number associated with bvn? I'm trying to verify using bvn but it's sending confirmation code to a phone number I no longer have access to.

**Comment by 4y0** [comment]
Hello @codeNgamer , You will have to visit your bank to do that

**Comment by codeNgamer** [comment]
@4y0 Thanks, cheers
